"""baseline existing schema

Revision ID: 9455ac29a85b
Revises: 
Create Date: 2026-09-29 01:25:01.233357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9455ac29a85b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kg_edge_source', table_name='kg_edges')
    op.drop_index('ix_kg_edge_target', table_name='kg_edges')
    op.drop_index('ix_kg_node_name', table_name='kg_nodes')
    op.drop_index('ix_notif_read_created', table_name='notifications')
    op.drop_index('ix_notif_user', table_name='notifications')
    op.alter_column('opportunities', 'related_technologies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'existing_research',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'evidence_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_opportunity_evidence_opp', table_name='opportunity_evidence')
    op.drop_index('ux_opportunity_evidence_opp_url', table_name='opportunity_evidence')
    op.create_index(op.f('ix_opportunity_evidence_id'), 'opportunity_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_evidence_opportunity_id'), 'opportunity_evidence', ['opportunity_id'], unique=False)
    op.drop_index('ix_opp_score_hist_opp', table_name='opportunity_score_history')
    op.drop_index('ix_opp_score_hist_time', table_name='opportunity_score_history')
    op.create_index(op.f('ix_opportunity_score_history_id'), 'opportunity_score_history', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_score_history_opportunity_id'), 'opportunity_score_history', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_score_history_recorded_at'), 'opportunity_score_history', ['recorded_at'], unique=False)
    op.drop_index('ux_organizations_canonical', table_name='organizations')
    op.create_index(op.f('ix_organizations_canonical_name'), 'organizations', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.alter_column('problem_papers', 'authors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'limitations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'research_methods',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'research_areas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_problem_papers_arxiv', table_name='problem_papers')
    op.drop_index('ix_problem_papers_profile', table_name='problem_papers')
    op.drop_index('ux_problem_papers_profile_arxiv', table_name='problem_papers')
    op.create_index(op.f('ix_problem_papers_arxiv_id'), 'problem_papers', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_problem_papers_id'), 'problem_papers', ['id'], unique=False)
    op.create_index(op.f('ix_problem_papers_problem_profile_id'), 'problem_papers', ['problem_profile_id'], unique=False)
    op.alter_column('problem_profiles', 'additional_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_profiles', 'affected_stakeholders',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_profiles', 'evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_problem_profiles_org_id', table_name='problem_profiles')
    op.create_index(op.f('ix_problem_profiles_organization_id'), 'problem_profiles', ['organization_id'], unique=False)
    op.alter_column('problem_technologies', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'potentially_applicable'::character varying"))
    op.drop_index('ix_problem_technologies_name', table_name='problem_technologies')
    op.drop_index('ix_problem_technologies_profile', table_name='problem_technologies')
    op.drop_index('ux_problem_technologies_profile_name', table_name='problem_technologies')
    op.create_index(op.f('ix_problem_technologies_id'), 'problem_technologies', ['id'], unique=False)
    op.create_index(op.f('ix_problem_technologies_problem_profile_id'), 'problem_technologies', ['problem_profile_id'], unique=False)
    op.create_index(op.f('ix_problem_technologies_technology_name'), 'problem_technologies', ['technology_name'], unique=False)
    op.drop_index('ix_recommendations_created', table_name='recommendations')
    op.drop_index('ix_recommendations_opp', table_name='recommendations')
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_opportunity_id'), 'recommendations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_trend_snapshots_id'), 'trend_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_snapshots_id'), table_name='trend_snapshots')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_opportunity_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.create_index('ix_recommendations_opp', 'recommendations', ['opportunity_id'], unique=False)
    op.create_index('ix_recommendations_created', 'recommendations', ['created_at'], unique=False)
    op.drop_index(op.f('ix_problem_technologies_technology_name'), table_name='problem_technologies')
    op.drop_index(op.f('ix_problem_technologies_problem_profile_id'), table_name='problem_technologies')
    op.drop_index(op.f('ix_problem_technologies_id'), table_name='problem_technologies')
    op.create_index('ux_problem_technologies_profile_name', 'problem_technologies', ['problem_profile_id', sa.text('lower(technology_name::text)')], unique=True)
    op.create_index('ix_problem_technologies_profile', 'problem_technologies', ['problem_profile_id'], unique=False)
    op.create_index('ix_problem_technologies_name', 'problem_technologies', ['technology_name'], unique=False)
    op.alter_column('problem_technologies', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'potentially_applicable'::character varying"))
    op.drop_index(op.f('ix_problem_profiles_organization_id'), table_name='problem_profiles')
    op.create_index('ix_problem_profiles_org_id', 'problem_profiles', ['organization_id'], unique=False)
    op.alter_column('problem_profiles', 'evidence',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_profiles', 'affected_stakeholders',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_profiles', 'additional_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_problem_papers_problem_profile_id'), table_name='problem_papers')
    op.drop_index(op.f('ix_problem_papers_id'), table_name='problem_papers')
    op.drop_index(op.f('ix_problem_papers_arxiv_id'), table_name='problem_papers')
    op.create_index('ux_problem_papers_profile_arxiv', 'problem_papers', ['problem_profile_id', 'arxiv_id'], unique=True)
    op.create_index('ix_problem_papers_profile', 'problem_papers', ['problem_profile_id'], unique=False)
    op.create_index('ix_problem_papers_arxiv', 'problem_papers', ['arxiv_id'], unique=False)
    op.alter_column('problem_papers', 'research_areas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'research_methods',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'limitations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('problem_papers', 'authors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_canonical_name'), table_name='organizations')
    op.create_index('ux_organizations_canonical', 'organizations', ['canonical_name'], unique=True)
    op.drop_index(op.f('ix_opportunity_score_history_recorded_at'), table_name='opportunity_score_history')
    op.drop_index(op.f('ix_opportunity_score_history_opportunity_id'), table_name='opportunity_score_history')
    op.drop_index(op.f('ix_opportunity_score_history_id'), table_name='opportunity_score_history')
    op.create_index('ix_opp_score_hist_time', 'opportunity_score_history', ['recorded_at'], unique=False)
    op.create_index('ix_opp_score_hist_opp', 'opportunity_score_history', ['opportunity_id'], unique=False)
    op.drop_index(op.f('ix_opportunity_evidence_opportunity_id'), table_name='opportunity_evidence')
    op.drop_index(op.f('ix_opportunity_evidence_id'), table_name='opportunity_evidence')
    op.create_index('ux_opportunity_evidence_opp_url', 'opportunity_evidence', ['opportunity_id', 'url'], unique=True)
    op.create_index('ix_opportunity_evidence_opp', 'opportunity_evidence', ['opportunity_id'], unique=False)
    op.alter_column('opportunities', 'evidence_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'existing_research',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'related_technologies',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_notif_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notif_read_created', 'notifications', ['read', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_kg_node_name', 'kg_nodes', ['name'], unique=False)
    op.create_index('ix_kg_edge_target', 'kg_edges', ['target'], unique=False)
    op.create_index('ix_kg_edge_source', 'kg_edges', ['source'], unique=False)
    # ### end Alembic commands ###
